local function load(name)
  require("plugins." .. name)
end

load("actions_preview")
load("blink")
load("bufdel")
load("bufferline")
load("comment")
load("conform")
load("fidget")
load("gitsigns")
load("indent_blankline")
load("lazydev")
load("lualine")
-- load("luasnip")
load("mason")
-- load("noice")
load("notify")
load("nvim_autopairs")
-- load("nvim_cmp")
load("nvim_dap")
load("nvim_dap_ui")
load("nvim_lspconfig")
load("nvim_tree")
load("nvim_treesitter")
load("nvim_web_devicons")
load("oil")
load("persistence")
load("smart_splits")
load("telescope")
load("todo_comments")
load("toggleterm")
load("trouble")
load("which_key")
