local function load(name)
  require("plugins." .. name)
end

load("bufdel")
load("bufferline")
load("conform")
load("indent_blankline")
load("lualine")
load("mason")
load("nvim_lspconfig")
load("nvim_tree")
load("nvim_treesitter")
load("oil")
load("telescope")
load("toggleterm")
load("trouble")
